"""empty message

Revision ID: 64cce118d067
Revises: bf33c9fd8a8a
Create Date: 2022-11-25 11:58:46.183779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cce118d067'
down_revision = 'bf33c9fd8a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('modify')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('modify')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify', sa.DATETIME(), nullable=True))
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify', sa.DATETIME(), nullable=True))
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
