"""empty message

Revision ID: bf33c9fd8a8a
Revises: b0c348c47b04
Create Date: 2022-11-25 11:19:55.755764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf33c9fd8a8a'
down_revision = 'b0c348c47b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('modify')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('modify')

    # ### end Alembic commands ###
